# Generated by Django 6.0.1 on 2026-04-22 04:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('diretor', 'Diretor'), ('professor', 'Professor'), ('aluno', 'Aluno')], max_length=10)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Portaria',
            fields=[
                ('id_portaria', models.AutoField(primary_key=True, serialize=False)),
                ('numero_portaria', models.CharField(max_length=50, unique=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('prazo_professor_criar_atividades', models.DateField(help_text='Data limite para professores criarem as atividades')),
                ('prazo_aluno_responder', models.DateField(help_text='Data limite para o aluno responder as atividades')),
                ('prazo_validacao_final', models.DateField(help_text='Data limite para conclusão de todo o processo')),
                ('status', models.CharField(choices=[('aguardando_atividades', 'Aguardando Criação de Atividades'), ('aguardando_respostas', 'Aguardando Respostas dos Alunos'), ('em_validacao_professor', 'Em Validação pelo Professor'), ('em_validacao_diretor', 'Em Validação pelo Diretor'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aguardando_atividades', max_length=30)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('motivo_portaria', models.TextField(help_text='Motivo da criação da portaria (ex: afastamento por doença)')),
            ],
            options={
                'verbose_name': 'Portaria',
                'verbose_name_plural': 'Portarias',
                'db_table': 'portaria',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.OneToOneField(db_column='id_admin', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='atividades.usuario')),
                ('nome_admin', models.CharField(max_length=150)),
                ('sobrenome_admin', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'admin_perfil',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.OneToOneField(db_column='id_aluno', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='atividades.usuario')),
                ('nome_aluno', models.CharField(max_length=150)),
                ('sobrenome_aluno', models.CharField(max_length=150)),
                ('curso_aluno', models.CharField(max_length=150)),
                ('periodo', models.CharField(max_length=150)),
                ('matricula_aluno', models.CharField(blank=True, max_length=150, null=True)),
                ('cursos', models.ManyToManyField(blank=True, db_table='aluno_curso', related_name='alunos', to='atividades.curso')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'aluno',
            },
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id_diretor', models.OneToOneField(db_column='id_diretor', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='atividades.usuario')),
                ('nome_diretor', models.CharField(max_length=150)),
                ('sobrenome_diretor', models.CharField(max_length=150)),
                ('curso_diretor', models.CharField(max_length=150)),
                ('curso_fk', models.ForeignKey(db_column='curso_fk', help_text='Curso que o diretor administra (obrigatório)', on_delete=django.db.models.deletion.PROTECT, related_name='diretores', to='atividades.curso')),
            ],
            options={
                'verbose_name': 'Diretor',
                'verbose_name_plural': 'Diretores',
                'db_table': 'diretor',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.OneToOneField(db_column='id_professor', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='atividades.usuario')),
                ('nome_professor', models.CharField(max_length=150)),
                ('sobrenome_professor', models.CharField(max_length=150)),
                ('curso_professor', models.CharField(max_length=150)),
                ('cursos', models.ManyToManyField(blank=True, db_table='professor_curso', related_name='professores', to='atividades.curso')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('codigo_disciplina', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nome_disciplina', models.CharField(max_length=50)),
                ('curso_fk', models.ForeignKey(db_column='curso_fk', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='atividades.curso')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'db_table': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='atividades.usuario')),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': 'Históricos',
                'db_table': 'historico',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id_notificacao', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('lida', models.BooleanField(default=False)),
                ('id_usuariodestino', models.ForeignKey(db_column='id_usuariodestino', on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='atividades.usuario')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'notificacao',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to='atividades.usuario')),
            ],
            options={
                'verbose_name': 'Token de Reset de Senha',
                'db_table': 'password_reset_token',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id_atividade', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('anexo', models.CharField(blank=True, help_text='Caminho do arquivo anexo à atividade', max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_limite_resposta', models.DateField(help_text='Data limite para o aluno responder (dentro do prazo da portaria)')),
                ('status', models.CharField(choices=[('aguardando_resposta', 'Aguardando Resposta do Aluno'), ('respondida', 'Respondida pelo Aluno'), ('validada_professor', 'Validada pelo Professor'), ('validada_diretor', 'Validada pelo Diretor'), ('rejeitada_professor', 'Rejeitada pelo Professor'), ('rejeitada_diretor', 'Rejeitada pelo Diretor')], default='aguardando_resposta', max_length=25)),
                ('codigo_disciplinafk', models.ForeignKey(db_column='codigo_disciplinafk', on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='atividades.disciplina')),
                ('id_portariafk', models.ForeignKey(db_column='id_portariafk', on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='atividades.portaria')),
                ('id_professorfk', models.ForeignKey(db_column='id_professorfk', on_delete=django.db.models.deletion.CASCADE, related_name='atividades_criadas', to='atividades.professor')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'db_table': 'atividade',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PortariaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_disciplinafk', models.ForeignKey(db_column='codigo_disciplinafk', on_delete=django.db.models.deletion.CASCADE, related_name='portarias_disciplina', to='atividades.disciplina')),
                ('id_portariafk', models.ForeignKey(db_column='id_portariafk', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas_portaria', to='atividades.portaria')),
            ],
            options={
                'verbose_name': 'Disciplina da Portaria',
                'verbose_name_plural': 'Disciplinas das Portarias',
                'db_table': 'portaria_disciplina',
                'unique_together': {('id_portariafk', 'codigo_disciplinafk')},
            },
        ),
        migrations.AddField(
            model_name='portaria',
            name='disciplinas',
            field=models.ManyToManyField(related_name='portarias', through='atividades.PortariaDisciplina', to='atividades.disciplina'),
        ),
        migrations.AddField(
            model_name='portaria',
            name='id_alunofk',
            field=models.ForeignKey(db_column='id_alunofk', on_delete=django.db.models.deletion.CASCADE, related_name='portarias', to='atividades.aluno'),
        ),
        migrations.AddField(
            model_name='portaria',
            name='id_diretorfk',
            field=models.ForeignKey(db_column='id_diretorfk', on_delete=django.db.models.deletion.CASCADE, related_name='portarias_criadas', to='atividades.diretor'),
        ),
        migrations.CreateModel(
            name='ProfessorDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateField(auto_now_add=True)),
                ('codigo_disciplinafk', models.ForeignKey(db_column='codigo_disciplinafk', on_delete=django.db.models.deletion.CASCADE, related_name='professores_disciplina', to='atividades.disciplina')),
                ('id_professorfk', models.ForeignKey(db_column='id_professorfk', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas_professor', to='atividades.professor')),
            ],
            options={
                'verbose_name': 'Professor-Disciplina',
                'verbose_name_plural': 'Professores-Disciplinas',
                'db_table': 'professor_disciplina',
                'unique_together': {('id_professorfk', 'codigo_disciplinafk')},
            },
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professores',
            field=models.ManyToManyField(related_name='disciplinas_lecionadas', through='atividades.ProfessorDisciplina', to='atividades.professor'),
        ),
        migrations.CreateModel(
            name='RespostaAtividade',
            fields=[
                ('id_resposta', models.AutoField(primary_key=True, serialize=False)),
                ('arquivo', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao_resposta', models.TextField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_validacao_professor', models.DateTimeField(blank=True, null=True)),
                ('observacao_professor', models.TextField(blank=True, null=True)),
                ('status_professor', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=25)),
                ('data_validacao_diretor', models.DateTimeField(blank=True, null=True)),
                ('observacao_diretor', models.TextField(blank=True, null=True)),
                ('status_diretor', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=25)),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Validação'), ('aprovada_professor', 'Pré-aprovada pelo Professor'), ('rejeitada_professor', 'Rejeitada pelo Professor'), ('aprovada_diretor', 'Validada pelo Diretor'), ('rejeitada_diretor', 'Rejeitada pelo Diretor')], default='pendente', max_length=25)),
                ('id_atividade', models.ForeignKey(db_column='id_atividade', on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='atividades.atividade')),
                ('id_alunofk', models.ForeignKey(db_column='id_alunofk', on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='atividades.aluno')),
            ],
            options={
                'verbose_name': 'Resposta de Atividade',
                'verbose_name_plural': 'Respostas de Atividades',
                'db_table': 'resposta_atividade',
                'ordering': ['-data_envio'],
                'unique_together': {('id_atividade', 'id_alunofk')},
            },
        ),
        migrations.CreateModel(
            name='AlunoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('codigo_disciplinafk', models.ForeignKey(db_column='codigo_disciplinafk', on_delete=django.db.models.deletion.CASCADE, related_name='alunos_matriculados', to='atividades.disciplina')),
                ('id_alunofk', models.ForeignKey(db_column='id_alunofk', on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='atividades.aluno')),
            ],
            options={
                'verbose_name': 'Matrícula em Disciplina',
                'verbose_name_plural': 'Matrículas em Disciplinas',
                'db_table': 'aluno_disciplina',
                'unique_together': {('id_alunofk', 'codigo_disciplinafk')},
            },
        ),
    ]
