# Generated by Django 6.0.1 on 2026-05-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaria',
            name='atestado',
            field=models.FileField(blank=True, help_text='Atestado médico ou documento comprobatório', null=True, upload_to='atestados/'),
        ),
    ]
