# Generated by Django 6.0.1 on 2026-05-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_add_ativo_to_pessoas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='status',
            field=models.CharField(choices=[('aguardando_resposta', 'Aguardando Resposta'), ('respondida', 'Respondida'), ('aprovada_professor', 'Aprovada pelo Professor'), ('reprovada_professor', 'Reprovada pelo Professor'), ('aprovada_diretor', 'Aprovada pelo Diretor'), ('reprovada_diretor', 'Reprovada pelo Diretor')], default='aguardando_resposta', max_length=25),
        ),
        migrations.AlterField(
            model_name='portaria',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_atividades', 'Aguardando Criação de Atividades'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=30),
        ),
        migrations.AlterField(
            model_name='respostaatividade',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada_prof', 'Aprovada pelo Professor'), ('rejeitada_prof', 'Rejeitada pelo Professor'), ('aprovada_dir', 'Aprovada pelo Diretor'), ('rejeitada_dir', 'Rejeitada pelo Diretor')], default='pendente', max_length=25),
        ),
    ]
